# Generated by Django 3.0.2 on 2020-02-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination_detail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination_detail',
        ),
    ]
