# Generated by Django 3.0.2 on 2020-02-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('day1', models.CharField(blank=True, max_length=255)),
                ('day1description', models.TextField(blank=True)),
                ('day2', models.CharField(blank=True, max_length=255)),
                ('day2description', models.TextField(blank=True)),
                ('day3', models.CharField(blank=True, max_length=255)),
                ('day3description', models.TextField(blank=True)),
                ('day4', models.CharField(blank=True, max_length=255)),
                ('day4description', models.TextField(blank=True)),
                ('day5', models.CharField(blank=True, max_length=255)),
                ('day5description', models.TextField(blank=True)),
                ('day6', models.CharField(blank=True, max_length=255)),
                ('day6description', models.TextField(blank=True)),
                ('day7', models.CharField(blank=True, max_length=255)),
                ('day7description', models.TextField(blank=True)),
                ('day8', models.CharField(blank=True, max_length=255)),
                ('day8description', models.TextField(blank=True)),
                ('day9', models.CharField(blank=True, max_length=255)),
                ('day9description', models.TextField(blank=True)),
                ('day10', models.CharField(blank=True, max_length=255)),
                ('day10description', models.TextField(blank=True)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='destination.Destination')),
            ],
        ),
    ]
