# Generated by Django 3.0.2 on 2020-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/sponsor'),
        ),
    ]
