# Generated by Django 3.0.2 on 2020-02-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_popularplaces_slider_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularplaces',
            old_name='price',
            new_name='prices',
        ),
    ]
