# Generated by Django 3.0.2 on 2020-02-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200210_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularplaces',
            name='prices',
        ),
    ]
