# Generated by Django 3.0.2 on 2020-02-16 07:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('blog_pic', models.ImageField(blank=True, upload_to='photos/blog')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('contact', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('guider', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getestimation', models.IntegerField()),
                ('homestayname', models.CharField(blank=True, max_length=200)),
                ('popularamenitities', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('pricedetail', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('pannumber', models.CharField(blank=True, max_length=200)),
                ('foodanddrinks', models.TextField(blank=True)),
                ('guestservice', models.TextField(blank=True)),
                ('outdoors', models.TextField(blank=True)),
                ('accessibility', models.TextField(blank=True)),
                ('homestaypicture', models.ImageField(blank=True, upload_to='photos/User/HomeStay')),
                ('room1pic', models.ImageField(blank=True, upload_to='photos/User/HomeStay')),
                ('room2pic', models.ImageField(blank=True, upload_to='photos/User/HomeStay')),
                ('outdoorpic', models.ImageField(blank=True, upload_to='photos/User/HomeStay')),
                ('citizenshipfront', models.ImageField(blank=True, upload_to='photos/User/HomeStay')),
                ('citizenshipback', models.ImageField(blank=True, upload_to='photos/User/HomeStay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestname', models.CharField(blank=True, max_length=200)),
                ('guestcontact', models.CharField(blank=True, max_length=200)),
                ('guestemail', models.CharField(blank=True, max_length=200)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime.now)),
                ('noofguest', models.IntegerField()),
                ('reasonforbooking', models.CharField(blank=True, max_length=200)),
                ('homestayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.HomeStay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
