# Generated by Django 3.0.2 on 2020-02-12 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('dob', models.DateField(blank=True, max_length=8)),
                ('contact', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('profilepic', models.ImageField(blank=True, upload_to='photos/user')),
                ('guider', models.CharField(blank=True, max_length=30)),
                ('document', models.ImageField(blank=True, upload_to='photos/documentation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
