# Generated by Django 3.0.2 on 2020-02-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='homestayid',
        ),
    ]
