# Generated by Django 3.0.2 on 2020-02-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('blog_pic', models.ImageField(blank=True, upload_to='photos/blog')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
