# Generated by Django 3.0.2 on 2020-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilepic',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, max_length=20),
        ),
    ]
