# Generated by Django 3.0 on 2020-02-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/slider/%y/%m/%d'),
        ),
    ]
