# Generated by Django 3.0.2 on 2020-02-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0002_auto_20200208_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
