# Generated by Django 3.0.2 on 2020-02-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0003_slider_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='body',
        ),
    ]
