# Generated by Django 3.0.2 on 2020-02-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0004_remove_slider_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/slider'),
        ),
    ]
