# Generated by Django 3.0.2 on 2020-02-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0005_auto_20200208_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
